package com.example.taskapp.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLightMediumContrast = Color(0xFF552C00)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFE69955)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF542C00)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF996029)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF552B00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF99602A)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F5)
val onBackgroundLightMediumContrast = Color(0xFF221A14)
val surfaceLightMediumContrast = Color(0xFFFFF8F5)
val onSurfaceLightMediumContrast = Color(0xFF17100A)
val surfaceVariantLightMediumContrast = Color(0xFFF3DFD2)
val onSurfaceVariantLightMediumContrast = Color(0xFF40342B)
val outlineLightMediumContrast = Color(0xFF5D5046)
val outlineVariantLightMediumContrast = Color(0xFF796A5F)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382F28)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFEEEE4)
val inversePrimaryLightMediumContrast = Color(0xFFFFB77B)
val surfaceDimLightMediumContrast = Color(0xFFD2C4BA)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F5)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1E9)
val surfaceContainerLightMediumContrast = Color(0xFFF5E5DB)
val surfaceContainerHighLightMediumContrast = Color(0xFFE9DAD0)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDECFC5)

val primaryDarkMediumContrast = Color(0xFFFFD4B4)
val onPrimaryDarkMediumContrast = Color(0xFF3D1E00)
val primaryContainerDarkMediumContrast = Color(0xFFC3824A)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFD4B3)
val onSecondaryDarkMediumContrast = Color(0xFF3D1E00)
val secondaryContainerDarkMediumContrast = Color(0xFFC28349)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD4B4)
val onTertiaryDarkMediumContrast = Color(0xFF3D1E00)
val tertiaryContainerDarkMediumContrast = Color(0xFFC3824A)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF19120C)
val onBackgroundDarkMediumContrast = Color(0xFFEFE0D6)
val surfaceDarkMediumContrast = Color(0xFF19120C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF51443B)
val onSurfaceVariantDarkMediumContrast = Color(0xFFECD9CB)
val outlineDarkMediumContrast = Color(0xFFC1AFA2)
val outlineVariantDarkMediumContrast = Color(0xFF9E8D82)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEFE0D6)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF312822)
val inversePrimaryDarkMediumContrast = Color(0xFF6D3C07)
val surfaceDimDarkMediumContrast = Color(0xFF19120C)
val surfaceBrightDarkMediumContrast = Color(0xFF4C433B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0603)
val surfaceContainerLowDarkMediumContrast = Color(0xFF241C16)
val surfaceContainerDarkMediumContrast = Color(0xFF2F2620)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3A312A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF453C35)

val pastelGreen = Color(0xFFA8CBB5)
val pastelRed = Color(0xFFEC447D)









